# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 40m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  skip-files:
    - ".*_mock_test.go"
    - ".*_example_test.go"

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

linters:
  enable-all: true
  disable:
    - maligned
  fast: false

linters-settings:
  lll:
    # max line length, lines longer will be reported. Default is 120. '\t' is counted as 1 character.
    line-length: 120

  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15

  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 100

  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8
